### ISSUE TITLE
The selected folder does not exist

### ISSUE THREAD

**Issue by kas2** [aconz2/Fusion360Exporter#5]
From     ...\Desktop\Fusion360Export\2020_09_22_15_56.txt:

Visiting file Cache_S8 v5 . f3d
Opening `Cache_S8`
Traceback (most recent call last):
  File "D:/Mes_Documents/documents/Temp/Exporter.py", line 216, in visit_file
    counter += export_file(ctx, format, file, doc)
  File "D:/Mes_Documents/documents/Temp/Exporter.py", line 184, in export_file
    options = em.createFusionArchiveExportOptions(str(output_path))
  File "C:/Users/yves/AppData/Local/Autodesk/webdeploy/production/4143a7d9c7cd58a0f86968fd3809be3e34945ca1/Api/Python/packages\adsk\fusion.py", line 13016, in createFusionArchiveExportOptions
    return _fusion.ExportManager_createFusionArchiveExportOptions(self, *args)
RuntimeError: 3 : The selected folder does not exist.

Should I create a folder before exporting ??
Please let me know what I am doing wrong
FWIW: Windows 10 (France)

**Comment by aconz2** [comment]
Confirmed bug, I introduced it a few changes ago and was able to reproduce it.

Fixed in https://github.com/aconz2/Fusion360Exporter/commit/4ee1a01a05aa8b95920bc94862819643979f950f

Re download the latest version (if you overwrite the old file you shouldn't have to re-add it to Fusion) and try again. If its fixed, please close the issue.

Thanks for reporting it

**Comment by kas2** [comment]
Thanks Andrew for your super fast reaction, works now like a charm
I suspect that lots of people are now trying to save their hard works,  following Autodesk 'smart move'

Thanks again, closing the issue
